apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
data:
  username: ZGJ1c2Vy
  password: ZGJwYXNzd29yZA==
  dbname: dG9kb2Ri
  rootpassword: cm9vdA==

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - args:
        - sh
        - -c 
        - cat /create-user.sql | envsubst > /docker-entrypoint-initdb.d/create-user.sql
        image: bhgedigital/envsubst:latest
        name: envsubst
        env:
         - name: DB_USER
           valueFrom:
             secretKeyRef:
              name: dbsecret
              key: username
         - name: DB_PASSWORD
           valueFrom:
              secretKeyRef:
                name: dbsecret
                key: password 
        volumeMounts:
        - name: mysql-inituser
          mountPath:  /create-user.sql
          subPath: create-user.sql
        - name: mysql-config
          mountPath: /docker-entrypoint-initdb.d
      containers:
      - name: mysql
        image: mysql:latest
       # args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        env:
          - name: DB_USER
            valueFrom:
             secretKeyRef:
              name: dbsecret
              key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: password
          - name: MYSQL_DATABASE
#            value: sample
            valueFrom:
             secretKeyRef:
              name: dbsecret
              key: dbname
          - name: MYSQL_ROOT_PASSWORD
#            value: root
            valueFrom:
             secretKeyRef:
              name: dbsecret
              key: rootpassword
#          - name: MYSQL_ROOT_HOST
#            value: 10.*.*.*
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-inituser
        configMap:
          name: dbusers
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: "100Mi"
  - metadata:
      name: mysql-config
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: "100Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbusers
data:
  create-user.sql: |-
    CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
    GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'%';

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306