apiVersion: v1
kind: Service
metadata:
   name: mysql
spec:
   type: NodePort
   selector:
      app: mysql
   ports:
   - port: 3306
     targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql-deployment
   labels:
      app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
         app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
         volumes:
         - name: mysql-pv
           persistentVolumeClaim:
              claimName: mysql-pv-claim
         containers:
            - name: mysql
              image: mysql_ravi:1.0
              #args: ["--default-authentication-plugin=mysql_native_password"]
              env:
              - name: MYSQL_ROOT_HOST
                value: "%"
#                valueFrom:
#                 secretKeyRef:
#                    name: mysql-root-pass
#                    key: password
              - name: MYSQL_ROOT_PASSWORD
                value: "root"
#                valueFrom:
#                 secretKeyRef:
#                    name: mysql-root-pass
#                    key: password
              - name: MYSQL_DATABASE
                value: "sample"
#                valueFrom:
#                 secretKeyRef:
#                   name: mysql-db
#                   key: database
              - name: MYSQL_USER
                value: "sample"
#                valueFrom:
#                 secretKeyRef:
#                   name: mysql-user-pass
#                   key: username
              - name: MYSQL_PASSWORD
                value: "sample"
#                valueFrom:
#                 secretKeyRef:
#                   name: mysql-user-pass
#                   key: password
              - name: MYSQL_ALLOW_EMPTY_PASSWORD
                value: "1"
#                valueFrom:
#                 secretKeyRef:
#                   name: mysql-user-pass
#                   key: password
              volumeMounts:
               - name: mysql-pv
                 mountPath: /var/lib/mysql
              ports:
              - containerPort: 3306
                name: mysql