apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app-container
          image: ravindrl/todoapiapp:1.0
          env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: dbuser
#            valueFrom:
#             secretKeyRef:
#              name: dbsecret
#              key: username
          - name: MYSQL_PASSWORD
            value: dbpassword
#            valueFrom:
#              secretKeyRef:
#                name: dbsecret
#                key: password
          - name: MYSQL_DB
            value: tododb
#            valueFrom:
#             secretKeyRef:
#              name: dbsecret
#              key: dbname
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort