apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysqlchart.fullname" . }}-dbusers
  labels:
  {{- include "mysqlchart.labels" . | nindent 4 }}
data:
  create-user.sql: {{ .Values.dbusers.createUserSql | toYaml | indent 1 }}