apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysqlchart.fullname" . }}-dbsecret
  labels:
  {{- include "mysqlchart.labels" . | nindent 4 }}
data:
  dbname: {{ required "dbsecret.dbname is required" .Values.dbsecret.dbname | b64enc
    | quote }}
  password: {{ required "dbsecret.password is required" .Values.dbsecret.password
    | b64enc | quote }}
  rootpassword: {{ required "dbsecret.rootpassword is required" .Values.dbsecret.rootpassword
    | b64enc | quote }}
  username: {{ required "dbsecret.username is required" .Values.dbsecret.username
    | b64enc | quote }}