apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.servicename}}
spec:
  type: {{ .Values.mysql.type }}
  selector:
    app: mysql
  ports:
	{{- .Values.mysql.ports | toYaml | nindent 2 -}}
